using System.Collections.Generic;

public class PersonalityGeneralizer {
	private static Dictionary<string, Personality> personalityMap = new Dictionary<string, Personality> { 
		{ "likes to discover new things", Personality.OPENNESS },
		{ "innocent", Personality.AGREEABLENESS },
		{ "a good listener", Personality.AGREEABLENESS },
		{ "can be seen as powercraving", Personality.NEUROTICISM },
		{ "Being ignored", Personality.NEUROTICISM },
		{ "compassion", Personality.CONSCIENTIOUS },
		{ "power-driven", Personality.NEUROTICISM },
		{ "impulsive", Personality.NEUROTICISM },
		{ "Being alone", Personality.NEUROTICISM },
		{ "being criticized", Personality.NEUROTICISM },
		{ "understanding", Personality.AGREEABLENESS },
		{ "Comfortable clothes", Personality.EXTRAVERSION },
		{ "energy", Personality.EXTRAVERSION },
		{ "easygoing", Personality.AGREEABLENESS },
		{ "likely to be female", Personality.CONSCIENTIOUS },
		{ "dull or boring situations", Personality.CONSCIENTIOUS },
		{ "loyal", Personality.CONSCIENTIOUS },
		{ "dedication", Personality.CONSCIENTIOUS },
		{ "enjoys luxury", Personality.NEUROTICISM },
		{ "Moody", Personality.EXTRAVERSION },
		{ "will-power", Personality.CONSCIENTIOUS },
		{ "conservative", Personality.CONSCIENTIOUS },
		{ "restful", Personality.CONSCIENTIOUS },
		{ "independent", Personality.CONSCIENTIOUS },
		{ "sophisticaled", Personality.CONSCIENTIOUS },
		{ "trusting", Personality.AGREEABLENESS },
		{ "optimistic", Personality.AGREEABLENESS },
		{ "strong will-power", Personality.CONSCIENTIOUS },
		{ "moody", Personality.NEUROTICISM },
		{ "Sudden changes", Personality.EXTRAVERSION },
		{ "sometimes comes across as arrogant", Personality.NEUROTICISM },
		{ "quiet", Personality.CONSCIENTIOUS },
		{ "empathy", Personality.AGREEABLENESS },
		{ "complications", Personality.NEUROTICISM },
		{ "can be seen as flaky", Personality.EXTRAVERSION },
		{ "calm", Personality.CONSCIENTIOUS },
		{ "helping loved ones", Personality.EXTRAVERSION },
		{ "wants too please too many people", Personality.EXTRAVERSION },
		{ "inflexible", Personality.CONSCIENTIOUS },
		{ "Impatient", Personality.NEUROTICISM },
		{ "Music", Personality.OPENNESS },
		{ "Assertive", Personality.EXTRAVERSION },
		{ "very energetic", Personality.EXTRAVERSION },
		{ "revealing of personal life", Personality.EXTRAVERSION },
		{ "sweet", Personality.AGREEABLENESS },
		{ "somestimes seems distant", Personality.NEUROTICISM },
		{ "friendship", Personality.EXTRAVERSION },
		{ "Sociable", Personality.EXTRAVERSION },
		{ "being admired", Personality.OPENNESS },
		{ "can get quite angry", Personality.NEUROTICISM },
		{ "independence", Personality.CONSCIENTIOUS },
		{ "humorous", Personality.OPENNESS },
		{ "faithful", Personality.CONSCIENTIOUS },
		{ "wise", Personality.CONSCIENTIOUS },
		{ "vitality", Personality.OPENNESS },
		{ "can feel quite guilty", Personality.CONSCIENTIOUS },
		{ "insecure", Personality.NEUROTICISM },
		{ "can be too delicate", Personality.NEUROTICISM },
		{ "Stubborn", Personality.NEUROTICISM },
		{ "sometimes seems distant", Personality.AGREEABLENESS },
		{ "the past coming back to haunt", Personality.OPENNESS },
		{ "cheerful", Personality.OPENNESS },
		{ "suspicious", Personality.OPENNESS },
		{ "openness to experience", Personality.OPENNESS },
		{ "practicality", Personality.CONSCIENTIOUS },
		{ "acceptance", Personality.AGREEABLENESS },
		{ "being lonely", Personality.NEUROTICISM },
		{ "youthful", Personality.OPENNESS },
		{ "relaxing near or in water", Personality.OPENNESS },
		{ "soothing", Personality.OPENNESS },
		{ "sleeping", Personality.OPENNESS },
		{ "Like attention", Personality.OPENNESS },
		{ "vigilance", Personality.OPENNESS },
		{ "fun with friends", Personality.OPENNESS },
		{ "romantic", Personality.OPENNESS },
		{ "responsible", Personality.CONSCIENTIOUS },
		{ "has a lot of passion", Personality.EXTRAVERSION },
		{ "Arrogant", Personality.NEUROTICISM },
		{ "Fearful", Personality.NEUROTICISM },
		{ "Runs from emotional expression", Personality.NEUROTICISM },
		{ "can be deceitful", Personality.EXTRAVERSION },
		{ "insecurity of any kind", Personality.NEUROTICISM },
		{ "fresh", Personality.OPENNESS },
		{ "sometimes scared of trying things", Personality.NEUROTICISM },
		{ "uncompromising", Personality.EXTRAVERSION },
		{ "happy", Personality.OPENNESS },
		{ "craving adventure", Personality.OPENNESS },
		{ "eco-concious", Personality.CONSCIENTIOUS },
		{ "likes learning new things", Personality.OPENNESS },
		{ "can be judgemental", Personality.CONSCIENTIOUS },
		{ "thrill seekers", Personality.OPENNESS },
		{ "warmth", Personality.AGREEABLENESS },
		{ "sensitive", Personality.AGREEABLENESS },
		{ "ful of energy and optimism", Personality.EXTRAVERSION },
		{ "too calm sometimes", Personality.AGREEABLENESS },
		{ "loving", Personality.AGREEABLENESS },
		{ "taking holidays", Personality.CONSCIENTIOUS },
		{ "traditional", Personality.AGREEABLENESS },
		{ "people who disagree with them", Personality.EXTRAVERSION },
		{ "delays", Personality.CONSCIENTIOUS },
		{ "determined", Personality.CONSCIENTIOUS },
		{ "intellectual conversation", Personality.OPENNESS },
		{ "home-based hobbies", Personality.OPENNESS },
		{ "sexual", Personality.EXTRAVERSION },
		{ "can be seen as vain", Personality.EXTRAVERSION },
		{ "stubborn", Personality.NEUROTICISM },
		{ "Extroverted", Personality.EXTRAVERSION },
		{ "sympathetic", Personality.AGREEABLENESS },
		{ "purity", Personality.AGREEABLENESS },
		{ "lazy", Personality.CONSCIENTIOUS },
		{ "cruelty of any kind", Personality.OPENNESS },
		{ "facing difficult reality", Personality.CONSCIENTIOUS },
		{ "confident", Personality.AGREEABLENESS },
		{ "self-control", Personality.CONSCIENTIOUS },
		{ "affectionate", Personality.AGREEABLENESS },
		{ "protection", Personality.AGREEABLENESS },
		{ "can be seen as authoritarian", Personality.NEUROTICISM },
		{ "mysterious", Personality.NEUROTICISM },
		{ "Not a strong attentionseeker", Personality.EXTRAVERSION },
		{ "cooking", Personality.OPENNESS },
		{ "Reliable", Personality.AGREEABLENESS },
		{ "tender", Personality.AGREEABLENESS },
		{ "likes to stand out", Personality.EXTRAVERSION },
		{ "wanting a sense of belonging", Personality.NEUROTICISM },
		{ "craves attention", Personality.NEUROTICISM },
		{ "Know-it-all", Personality.NEUROTICISM },
		{ "repetition and routine", Personality.CONSCIENTIOUS },
		{ "fear of being trapped", Personality.NEUROTICISM },
		{ "inconsistent", Personality.EXTRAVERSION },
		{ "broken promises", Personality.CONSCIENTIOUS },
		{ "likely to be male", Personality.AGREEABLENESS },
		{ "can be very emotional at times", Personality.AGREEABLENESS },
		{ "trustworthy", Personality.AGREEABLENESS },
		{ "highly imaginative", Personality.OPENNESS },
		{ "mature", Personality.CONSCIENTIOUS },
		{ "can be seen as arrogant", Personality.NEUROTICISM },
		{ "Limitations", Personality.OPENNESS },
		{ "can be jealous", Personality.NEUROTICISM },
		{ "wants to change everything", Personality.CONSCIENTIOUS },
		{ "short trips around the town", Personality.EXTRAVERSION },
		{ "pessimistic", Personality.NEUROTICISM },
		{ "Creative", Personality.OPENNESS },
		{ "ambitious", Personality.OPENNESS },
		{ "has a sad side to them", Personality.AGREEABLENESS },
		{ "credibility", Personality.AGREEABLENESS },
		{ "curious", Personality.OPENNESS },
		{ "health concious", Personality.CONSCIENTIOUS },
		{ "being confined", Personality.NEUROTICISM },
		{ "work that does not use one's talents", Personality.AGREEABLENESS },
		{ "excitement", Personality.EXTRAVERSION },
		{ "openminded", Personality.OPENNESS },
		{ "strives for wealth", Personality.EXTRAVERSION },
		{ "overly trusting", Personality.AGREEABLENESS },
		{ "like things to be in balance", Personality.CONSCIENTIOUS },
		{ "passionate", Personality.AGREEABLENESS },
		{ "full of energy and optimism", Personality.EXTRAVERSION },
		{ "can be stubborn", Personality.NEUROTICISM },
		{ "agressive", Personality.EXTRAVERSION },
		{ "helping others", Personality.AGREEABLENESS },
		{ "is very creative", Personality.OPENNESS },
		{ "patient", Personality.AGREEABLENESS },
		{ "generous", Personality.AGREEABLENESS },
		{ "a good meal with friends", Personality.AGREEABLENESS },
		{ "idealistic", Personality.OPENNESS },
		{ "chats with nearly anyone", Personality.EXTRAVERSION },
		{ "Introverted", Personality.EXTRAVERSION },
		{ "ability to learn quickly and exchange ideas", Personality.OPENNESS },
		{ "indecisive", Personality.EXTRAVERSION },
		{ "desire to escape reality", Personality.OPENNESS },
		{ "Nervous", Personality.NEUROTICISM },
		{ "caring", Personality.AGREEABLENESS },
		{ "stable", Personality.CONSCIENTIOUS },
		{ "can be envious", Personality.NEUROTICISM },
		{ "dignity", Personality.OPENNESS },
		{ "spiritual", Personality.OPENNESS },
		{ "self-centered", Personality.NEUROTICISM },
	};

	public static Personality getPersonality(string trait) {
		return personalityMap[trait];
	}
}